language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
install:
    - cpanm --notest App::FatPacker Git::Sub || { cat ~/.cpanm/build.log ; false ; }
    - cpanm --reinstall --notest Config::Perl::V JSON::PP || { cat ~/.cpanm/build.log ; false ; }
    - perl build.pl
script:
    - perl ./perlinfo.json.pl
